print("welcome to the game username creator")
name = input("what is your name?\n")
fav_game = input("what is your favourite game?\n")
age = input("how old are you?\n")
fav_color = input("what is your favourite color?\n")
print("\nhere are 8 gaming username ideas:\n")
print("1.",name, fav_game)
print("2.",name, age)
print("3.",name, fav_color)
print("4.",fav_game, fav_color)
print("5.",fav_game, age)
print("6.",fav_color, name)
print("7.",name, "gamer")
print("8.",fav_color, fav_game)
print("name length:",len(name))
print("age length:",len(age))
print("fav_color length:",len(fav_color))
print("fav_game length:",len(fav_game))
print("your name data type is:",type(name))
print("\nThank you for using the Game Username Creator!")